import { requireChromeExecutable } from "./platform-runtime.mjs";
import test from "node:test";
import path from "node:path";
import os from "node:os";
import assert from "node:assert/strict";
import { chromium } from "playwright-core";
import { candidateCapturePaths, expandTsdrVerificationSections, tsdrRenderedSnapshot } from "./cdp-cli.mjs";

const CHROME = requireChromeExecutable();
const field = (label, value) => `<div class="row"><div class="key">${label}:</div><div class="value">${value}</div></div>`;
const section = (label, content, key = label) => `<div class="expand_wrapper default_hide"><h2 class="expand_heading"><span data-sectiontitle="${key}"><a class="sectionLink" href="javascript:;">${label}</a></span></h2><div class="toggle_container" style="display:none"><div class="sectionContainer">${content}</div></div></div>`;
const RECORD = `<div>Status results found</div><div id="summary">
  ${field("Mark", "MELLA")}${field("US Serial Number", "97876463")}${field("US Registration Number", "7366451")}
  ${field("Status", "Registered. The registration date is used to determine when post-registration maintenance documents are due.")}
  ${field("Status Date", "Apr. 23, 2024")}${field("Generated on", "This page was generated by TSDR")}</div>
  ${section("Goods and Services", field("For", "Elastomer hookless tie-down straps; elastomer tie-down straps") + field("International Class(es)", "022 - Primary Class") + field("U.S Class(es)", "001,002,007,019,022,042,050"))}
  ${section("Basis Information (Case Level)", field("Status", "unrelated"))}
  ${section("Current Owner(s) Information", field("Owner Name", "49th and Monroe Ltd."))}
  ${section("Mark Information", field("Design Search Code(s)", "26.17.01 - Straight lines") + field("Description of Mark", "The mark consists of three parallel lines.") + field("Mark Drawing Type", "3 - AN ILLUSTRATION DRAWING WHICH INCLUDES WORD(S)/LETTER(S)/NUMBER(S)"), "markInformation")}
  <div id="other">${field("Owner Name", "Unrelated outside current owner section")}</div>`;

async function recordPage(browser) {
  const page = await browser.newPage();
  await page.setContent(RECORD);
  await page.locator("a.sectionLink").evaluateAll(links => links.forEach(link => {
    link.onclick = event => {
      event.preventDefault();
      link.dataset.clicks = String(Number(link.dataset.clicks || 0) + 1);
      const content = link.closest(".expand_wrapper").querySelector(".toggle_container");
      content.style.display = content.style.display === "none" ? "block" : "none";
    };
  }));
  return page;
}

test("TSDR rendered fields ignore top status banner and collapsed section headings", async () => {
  const browser = await chromium.launch({ executablePath: CHROME, headless: true });
  try {
    const page = await recordPage(browser);
    const row = await tsdrRenderedSnapshot(page);
    assert.equal(row.page_case_number, "97876463");
    assert.equal(row.registration_number, "7366451");
    assert.equal(row.mark_text, "MELLA");
    assert.match(row.case_status, /^Registered\./);
    assert.notEqual(row.case_status, "results found");
    assert.deepEqual(row.owners, []);
    assert.deepEqual(row.goods_services, []);
    assert.deepEqual(row.classes, []);
    assert.deepEqual(row.design_codes, []);
  } finally { await browser.close(); }
});

test("TSDR expands only exact record sections and reads Nice classes, idempotently", async () => {
  const browser = await chromium.launch({ executablePath: CHROME, headless: true });
  try {
    const page = await recordPage(browser);
    assert.deepEqual(await expandTsdrVerificationSections(page, "97876463"), ["Goods and Services", "Current Owner(s) Information"]);
    const row = await tsdrRenderedSnapshot(page);
    assert.deepEqual(row.owners, ["49th and Monroe Ltd."]);
    assert.deepEqual(row.goods_services, ["Elastomer hookless tie-down straps; elastomer tie-down straps"]);
    assert.deepEqual(row.classes, ["022"]);
    assert.deepEqual(await expandTsdrVerificationSections(page, "97876463"), []);
    assert.deepEqual(await page.locator("a.sectionLink").evaluateAll(links => links.map(link => Number(link.dataset.clicks || 0))), [1, 0, 1, 0]);
    await page.locator('[data-sectiontitle="markInformation"] a').click();
    assert.deepEqual((await tsdrRenderedSnapshot(page)).design_codes, ["26.17.01 - Straight lines"]);
  } finally { await browser.close(); }
});

test("TSDR never opens controls for another serial or ambiguous section", async () => {
  const browser = await chromium.launch({ executablePath: CHROME, headless: true });
  try {
    const page = await recordPage(browser);
    await assert.rejects(() => expandTsdrVerificationSections(page, null), /IDENTITY_MISMATCH/);
    await assert.rejects(() => expandTsdrVerificationSections(page, "11111111"), /IDENTITY_MISMATCH/);
    assert.equal(await page.locator("a[data-clicks]").count(), 0);
    await page.locator("body").evaluate((body, html) => body.insertAdjacentHTML("beforeend", html), section("Goods and Services", field("For", "Other goods")));
    await assert.rejects(() => expandTsdrVerificationSections(page, "97876463"), /SECTION_CONTROL_UNAVAILABLE/);
    assert.equal(await page.locator("a[data-clicks]").count(), 0);
  } finally { await browser.close(); }
});

test("figurative verification uses TSDR's markInformation key and Code(s) label without reclicking complete sections", async () => {
  const browser = await chromium.launch({ executablePath: CHROME, headless: true });
  try {
    const page = await recordPage(browser);
    await expandTsdrVerificationSections(page, "97876463");
    assert.deepEqual(await expandTsdrVerificationSections(page, "97876463", { markInformation: true }), ["Mark Information"]);
    const fields = await tsdrRenderedSnapshot(page);
    assert.match(fields.mark_description, /parallel lines/);
    assert.match(fields.mark_drawing_type, /^3/);
    assert.deepEqual(fields.design_codes, ["26.17.01 - Straight lines"]);
    assert.equal(fields.mark_information.section_observed, true);
    assert.deepEqual(await expandTsdrVerificationSections(page, "97876463", { markInformation: true }), []);
    assert.deepEqual(await page.locator("a.sectionLink").evaluateAll(links => links.map(link => Number(link.dataset.clicks || 0))), [1, 0, 1, 1]);
  } finally { await browser.close(); }
});

test("strict TSDR retries have unique capture, screenshot and official-mark evidence paths", () => {
  const taskDir = path.join(os.tmpdir(), "tsdr-task");
  const args = [taskDir, "uspto_tsdr", "97876463", "QRY-test", { screening_revision: "recall-integrity-v1" }];
  const first = candidateCapturePaths(...args), second = candidateCapturePaths(...args);
  for (const key of ["capturePath", "screenshotPath", "markImagePath"]) {
    assert.notEqual(first[key], second[key]);
    assert.match(first[key], /uspto_tsdr-QRY-test-/);
  }
  const legacy = candidateCapturePaths(...args.slice(0, 4));
  assert.equal(legacy.capturePath, path.join(taskDir, "uspto_tsdr-97876463-capture.json"));
  assert.equal(legacy.screenshotPath, path.join(taskDir, "screenshots", "uspto_tsdr-97876463.png"));
  assert.equal(legacy.markImagePath, path.join(taskDir, "images", "uspto-tsdr-97876463-official-mark.png"));
});
